# Copyright (c) 2013 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

description: Apps and Engines when launching with a project only context.

#################################################################################################
# include common definitions for all the launchers that are used to start maya, nuke etc.

includes: [./includes/app_launchers.yml, ./includes/common_apps.yml]


#################################################################################################
# define all the items that should appear in this environment

engines:

  tk-desktop:
    apps:
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-screeningroom: '@launch_screeningroom'
    collapse_rules:
    - {button_label: $app, match: Launch $app, menu_label: None}
    debug_logging: false
    default_group: Studio
    groups:
    - matches: ['*Hiero*', '*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*', '*Photoshop*', '*Softimage*']
      name: Creative Tools
    hook_launch_python: default
    location: {name: tk-desktop, type: app_store, version: v1.0.2}
    show_recents: true
    
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles-launch-at-startup'
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.4.2}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
    
  tk-nuke:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location: {name: tk-nuke, type: app_store, version: v0.2.24}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
    
  tk-photoshop:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles'
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.3.2}
    
  tk-shell:
    apps:
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-screeningroom: '@launch_screeningroom'
    location: {name: tk-shell, type: app_store, version: v0.4.0}
    
frameworks:
  tk-framework-adminui_v0.x.x:
    location: {name: tk-framework-adminui, type: app_store, version: v0.0.7}
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.0.2}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
